services:
  db:
    image: postgres:latest
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./db/data:/var/lib/postgresql/data
